{% set name = "trulens-connectors-snowflake" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trulens_connectors_snowflake-{{ version }}.tar.gz
    sha256: a7aa5eb9a1ffa98e2301952473a958f4bd143d2723339bc926f0a675e6d48ade
  # License is not included in tarball, pulling from github for now
  # Remove this when upstream includes it in pypi release
  - url: https://raw.githubusercontent.com/truera/trulens/refs/tags/trulens-1.1.0/LICENSE
    sha256: cbc129d2a89ca1684a46c719a8e75b7f3602a5f00d6c17a12ec9c49a7cfa3d33

build:
  skip: True  # [py<39 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 100

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - trulens-core >=1.0.0,<2.0.0
    - snowflake.core >=0.8.0
    - snowflake-connector-python >=3.11.0,<4.0.0
    - snowflake-snowpark-python >=1.18.0,<2.0.0
    - snowflake-sqlalchemy >=1.6.0,<2.0.0

test:
  imports:
    - trulens.connectors.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/truera/trulens
  doc_url: https://www.trulens.org/getting_started/
  description: Library to systematically track and evaluate LLM based applications.

extra:
  recipe-maintainers:
    - Cansisti
